CREATE USER IF NOT EXISTS 'dev'@'%' IDENTIFIED BY 'dev';

CREATE DATABASE IF NOT EXISTS dev;

ALTER DATABASE dev
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON dev.* TO 'dev'@'%' IDENTIFIED BY 'dev';